### PR TITLE
fix memory usage for posix_memalign

### PR DESCRIPTION
**Pull request by hannesm**
Dear @palainp, I prepared here a PR of your branch to track and review it properly. :) Thanks for your investigation and work.

Indeed, in the solo5-hvt/spt/virtio setting, the posix_memalign is never called as far as I can tell -- but xen requires it (due to io-page).

### CODE REVIEW

**Comment by hannesm** [comment]
to me, this looks fine. happy to see further reviews. @palainp also please indicate whether you're happy with your commit :)

**Comment by palainp** [comment]
Thank you @hannesm , this change is ok to me with qubes-mirage-firewall after some hours of running (I saw free memory going up and down as expected).

**Comment by hannesm** [comment]
thank you for your work, I cut the 0.8.4 release with your fix https://github.com/ocaml/opam-repository/pull/25717

**Comment by palainp** [comment]
Thanks! I'll update qubes-mirage-firewall with that realease :)

**Pull request merged**
